# Generated by Django 3.2 on 2023-04-06 04:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_review_unique_title_author'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_title_author',
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10, 'Значение не должно быть больше 10.'), django.core.validators.MinValueValidator(1, 'Значение не должно быть меньше 1.')]),
        ),
    ]
